# Generated by Django 5.2.14 on 2026-08-21 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=50, unique=True, verbose_name='Part Number')),
                ('part_name', models.CharField(max_length=200, verbose_name='Part Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('unit_price', models.FloatField(default=0.0, verbose_name='Unit Price')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Stock Quantity')),
                ('minimum_stock', models.IntegerField(default=0, verbose_name='Minimum Stock')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Spare Part',
                'verbose_name_plural': 'Spare Parts',
                'db_table': 'spare_parts',
                'ordering': ['part_number'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SparePartAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Username')),
                ('password_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Spare Part Portal Account',
                'verbose_name_plural': 'Spare Part Portal Accounts',
                'db_table': 'spare_part_auth',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SparePartTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(verbose_name='Transaction Date')),
                ('transaction_type', models.CharField(choices=[('IN', 'Incoming'), ('OUT', 'Outgoing')], max_length=3, verbose_name='Transaction Type')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('unit_price', models.FloatField(default=0.0, verbose_name='Unit Price')),
                ('total_amount', models.FloatField(default=0.0, verbose_name='Total Amount')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(db_column='part_id', on_delete=django.db.models.deletion.CASCADE, to='spare_parts.sparepart', verbose_name='Spare Part')),
            ],
            options={
                'verbose_name': 'Spare Part Transaction',
                'verbose_name_plural': 'Spare Part Transactions',
                'db_table': 'spare_part_transactions',
                'ordering': ['-transaction_date'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SparePartLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(verbose_name='Entry Date')),
                ('opening_balance', models.IntegerField(default=0, verbose_name='Opening Balance')),
                ('quantity_in', models.IntegerField(default=0, verbose_name='Quantity In')),
                ('quantity_out', models.IntegerField(default=0, verbose_name='Quantity Out')),
                ('closing_balance', models.IntegerField(default=0, verbose_name='Closing Balance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(db_column='part_id', on_delete=django.db.models.deletion.CASCADE, to='spare_parts.sparepart', verbose_name='Spare Part')),
                ('transaction', models.ForeignKey(db_column='transaction_id', on_delete=django.db.models.deletion.CASCADE, to='spare_parts.spareparttransaction', verbose_name='Transaction')),
            ],
            options={
                'verbose_name': 'Spare Part Ledger',
                'verbose_name_plural': 'Spare Part Ledgers',
                'db_table': 'spare_part_ledger',
                'ordering': ['-entry_date', 'part'],
                'managed': True,
            },
        ),
    ]
