# Generated by Django 4.2 on 2026-05-24 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cnic', models.CharField(max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100, null=True)),
                ('business_name', models.CharField(max_length=100, null=True)),
                ('normalized_business_name', models.CharField(max_length=100, null=True, unique=True)),
                ('ntn', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('DEALER', 'Dealer')], default='INDIVIDUAL', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinanceCreditSale',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sale_id', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('chassis_no', models.CharField(max_length=50)),
                ('engine_no', models.CharField(max_length=50, null=True)),
                ('model', models.CharField(max_length=50, null=True)),
                ('cash_price', models.FloatField(default=0.0)),
                ('credit_price', models.FloatField(default=0.0)),
                ('down_payment', models.FloatField(default=0.0)),
                ('down_payment_method', models.CharField(default='Cash', max_length=50)),
                ('duration_months', models.IntegerField(default=0)),
                ('duration_days', models.IntegerField(default=0)),
                ('installment_amount', models.FloatField(default=0.0)),
                ('sale_date', models.DateTimeField()),
                ('due_date', models.DateTimeField(null=True)),
                ('remaining_balance', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('OVERDUE', 'Overdue')], default='ACTIVE', max_length=20)),
                ('credit_type', models.CharField(default='Advanced Separate Finance', max_length=50)),
                ('notes', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'finance_credit_sales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinanceInstallment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_id', models.CharField(max_length=50, unique=True)),
                ('paid_amount', models.FloatField()),
                ('payment_date', models.DateTimeField()),
                ('payment_method', models.CharField(default='Cash', max_length=50)),
                ('reference_no', models.CharField(max_length=50, null=True)),
                ('notes', models.CharField(max_length=500, null=True)),
                ('loan_id', models.IntegerField(null=True)),
                ('installment_no', models.IntegerField(null=True)),
                ('due_date', models.DateTimeField(null=True)),
                ('principal_due', models.FloatField(default=0.0)),
                ('interest_due', models.FloatField(default=0.0)),
                ('fees_due', models.FloatField(default=0.0)),
                ('total_due', models.FloatField(default=0.0)),
                ('late_fee_accrued', models.FloatField(default=0.0)),
                ('late_fee_last_calculated_at', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('PARTIAL', 'Partial')], default='PAID', max_length=20)),
                ('paid_principal', models.FloatField(default=0.0)),
                ('paid_interest', models.FloatField(default=0.0)),
                ('paid_fees', models.FloatField(default=0.0)),
                ('paid_total', models.FloatField(default=0.0)),
                ('paid_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'finance_installments',
                'ordering': ['-payment_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinanceLedger',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ledger_id', models.CharField(max_length=50, unique=True)),
                ('entry_type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500, null=True)),
                ('debit', models.FloatField(default=0.0)),
                ('credit', models.FloatField(default=0.0)),
                ('balance', models.FloatField(default=0.0)),
                ('entry_date', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'finance_ledger',
                'ordering': ['-entry_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('vin', models.CharField(max_length=50, null=True, unique=True)),
                ('chassis_number', models.CharField(max_length=50, unique=True)),
                ('engine_number', models.CharField(max_length=50, unique=True)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=30, null=True)),
                ('cost_price', models.FloatField()),
                ('sale_price', models.FloatField()),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('SOLD', 'Sold')], default='IN_STOCK', max_length=20)),
                ('purchase_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'motorcycles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=50, unique=True)),
                ('make', models.CharField(default='Honda', max_length=50)),
                ('engine_capacity', models.CharField(max_length=20, null=True)),
                ('pct_code', models.CharField(max_length=20, null=True)),
                ('item_code', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'product_models',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerPortalAuth',
            fields=[
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='portal.customer')),
            ],
            options={
                'db_table': 'customer_portal_auth',
                'managed': True,
            },
        ),
    ]
