# Generated by Django 5.2.14 on 2026-08-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_customerportalauth_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerLedger',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('chassis_number', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('debit', models.FloatField(default=0.0)),
                ('credit', models.FloatField(default=0.0)),
                ('balance', models.FloatField(default=0.0)),
                ('reference_id', models.IntegerField(null=True)),
                ('reference_type', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'buyer_ledger',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CreditPayment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('penalty_amount', models.FloatField(default=0.0)),
                ('discount_amount', models.FloatField(default=0.0)),
                ('net_amount', models.FloatField()),
                ('payment_mode', models.CharField(default='Cash', max_length=50)),
                ('invoice_reference', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'credit_payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CreditSale',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sale_date', models.DateTimeField()),
                ('buyer_type', models.CharField(max_length=20)),
                ('duration_months', models.IntegerField(default=0)),
                ('duration_days', models.IntegerField(default=0)),
                ('total_cash_price', models.FloatField(default=0.0)),
                ('total_credit_price', models.FloatField(default=0.0)),
                ('advance_payment', models.FloatField(default=0.0)),
                ('advance_payment_mode', models.CharField(default='Cash', max_length=50)),
                ('remaining_amount', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('OVERDUE', 'Overdue')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'credit_sales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CreditSaleItem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('chassis_number', models.CharField(max_length=50, unique=True)),
                ('model', models.CharField(max_length=50, null=True)),
                ('color', models.CharField(max_length=30, null=True)),
                ('cash_price', models.FloatField()),
                ('credit_price', models.FloatField()),
            ],
            options={
                'db_table': 'credit_sale_items',
                'managed': False,
            },
        ),
    ]
