# Generated by Django 5.2.14 on 2026-09-18 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_buyerledger_creditpayment_creditsale_creditsaleitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('father', models.CharField(max_length=100, null=True)),
                ('cnic', models.CharField(max_length=20, null=True)),
                ('cell', models.CharField(max_length=20, null=True)),
                ('chassis_number', models.CharField(max_length=50, null=True)),
                ('engine_number', models.CharField(max_length=50, null=True)),
                ('model', models.CharField(max_length=50, null=True)),
                ('color', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'captured_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpareLedgerMonthlyClose',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('month_key', models.CharField(max_length=7, unique=True)),
                ('closed_at', models.DateTimeField()),
                ('opening_balance', models.FloatField(default=0.0)),
                ('total_credits', models.FloatField(default=0.0)),
                ('total_debits', models.FloatField(default=0.0)),
                ('closing_balance', models.FloatField(default=0.0)),
                ('carried_forward', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('CLOSED', 'Closed')], default='CLOSED', max_length=10)),
            ],
            options={
                'db_table': 'spare_ledger_monthly_close',
                'ordering': ['-month_key'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpareLedgerTransaction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('trans_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('amount', models.FloatField()),
                ('reference_number', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('cash_type', models.CharField(choices=[('BANK', 'Bank'), ('HARD_CASH', 'Cash')], default='HARD_CASH', max_length=20)),
                ('created_by_user_id', models.IntegerField(null=True)),
                ('month_key', models.CharField(max_length=7, null=True)),
            ],
            options={
                'db_table': 'spare_ledger_transactions',
                'ordering': ['-timestamp'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StaffAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_dashboard', 'View admin dashboard'), ('view_customers', 'View customers'), ('view_customer_summary', 'View customer summary'), ('view_sales', 'View credit sales'), ('view_payments', 'View payments'), ('view_inventory', 'View inventory'), ('view_transactions', 'View transaction history'), ('view_portal_accounts', 'View customer portal accounts'), ('manage_portal_accounts', 'Create/reset/block customer portal accounts'), ('view_old_credit_ledger', 'View old running credit ledger'), ('view_finance_credit_ledger', 'View advance separate finance ledger'), ('view_combined_ledger', 'View combined credit ledger'), ('view_spare_ledger', 'View spare parts ledger'), ('export_data', 'Export sales/payments to CSV')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff')], default='STAFF', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portal_user_profile',
            },
        ),
    ]
