# Generated by Django 5.2.14 on 2026-09-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_staffaccess_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBRConfiguration',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('environment', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('api_base_url', models.CharField(max_length=255)),
                ('pos_id', models.CharField(blank=True, max_length=50, null=True)),
                ('usin', models.CharField(blank=True, max_length=50, null=True)),
                ('auth_token', models.CharField(blank=True, max_length=500, null=True)),
                ('secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_rate', models.FloatField(default=18.0)),
                ('invoice_type', models.CharField(default='Standard', max_length=20)),
                ('discount', models.FloatField(default=0.0)),
                ('pos_fee', models.FloatField(default=1.0)),
                ('pct_code', models.CharField(default='8711.2010', max_length=20)),
                ('item_code', models.CharField(blank=True, max_length=50, null=True)),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('business_name', models.CharField(blank=True, default='Ehsan Trader', max_length=100, null=True)),
            ],
            options={
                'db_table': 'fbr_configurations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('pos_id', models.CharField(max_length=20)),
                ('usin', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField(null=True)),
                ('total_sale_value', models.FloatField()),
                ('total_tax_charged', models.FloatField()),
                ('total_further_tax', models.FloatField(default=0.0)),
                ('total_quantity', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('discount', models.FloatField(default=0.0)),
                ('payment_mode', models.CharField(default='Cash', max_length=20)),
                ('fbr_invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_fiscalized', models.BooleanField(default=False)),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('fbr_response_code', models.CharField(blank=True, max_length=10, null=True)),
                ('fbr_response_message', models.CharField(blank=True, max_length=255, null=True)),
                ('fbr_full_response', models.JSONField(blank=True, null=True)),
                ('status_updated_at', models.DateTimeField(null=True)),
                ('upload_attempts', models.IntegerField(default=0)),
                ('max_upload_attempts', models.IntegerField(default=5)),
                ('upload_priority', models.IntegerField(default=0)),
                ('is_processing', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'invoices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=100)),
                ('pct_code', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.FloatField()),
                ('tax_rate', models.FloatField()),
                ('sale_value', models.FloatField()),
                ('tax_charged', models.FloatField()),
                ('further_tax', models.FloatField(default=0.0)),
                ('total_amount', models.FloatField()),
                ('discount', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'invoice_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('base_price', models.FloatField()),
                ('tax_amount', models.FloatField()),
                ('levy_amount', models.FloatField()),
                ('total_price', models.FloatField()),
                ('optional_features', models.JSONField(blank=True, null=True)),
                ('effective_date', models.DateTimeField(null=True)),
                ('expiration_date', models.DateTimeField(null=True)),
                ('currency', models.CharField(default='Rs', max_length=10)),
            ],
            options={
                'db_table': 'prices',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='staffaccess',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_dashboard', 'View admin dashboard'), ('view_customers', 'View customers'), ('view_customer_summary', 'View customer summary'), ('view_sales', 'View credit sales'), ('view_payments', 'View payments'), ('view_inventory', 'View inventory'), ('view_transactions', 'View transaction history'), ('view_portal_accounts', 'View customer portal accounts'), ('manage_portal_accounts', 'Create/reset/block customer portal accounts'), ('view_old_credit_ledger', 'View old running credit ledger'), ('view_finance_credit_ledger', 'View advance separate finance ledger'), ('view_combined_ledger', 'View combined credit ledger'), ('view_spare_ledger', 'View spare parts ledger'), ('export_data', 'Export sales/payments to CSV'), ('manage_customers', 'Add/edit customer records'), ('manage_product_models', 'Add/edit/delete product models'), ('manage_inventory', 'Add/edit/delete motorcycles'), ('manage_finance_sales', 'Add/edit/delete finance credit sales'), ('manage_finance_installments', 'Add/edit/delete finance installments'), ('manage_finance_ledger', 'Add/edit/delete finance ledger entries'), ('view_invoices', 'View submitted sales invoices'), ('create_invoices', 'Create new sales invoices and upload them to FBR')]},
        ),
    ]
