# Generated by Django 5.2.14 on 2026-09-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_staffaccess_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('ntn', models.CharField(blank=True, max_length=20, null=True)),
                ('cnic', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'companies',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='staffaccess',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_dashboard', 'View admin dashboard'), ('view_customers', 'View customers'), ('view_customer_summary', 'View customer summary'), ('view_sales', 'View credit sales'), ('view_payments', 'View payments'), ('view_inventory', 'View inventory'), ('view_transactions', 'View transaction history'), ('view_portal_accounts', 'View customer portal accounts'), ('manage_portal_accounts', 'Create/reset/block customer portal accounts'), ('view_old_credit_ledger', 'View old running credit ledger'), ('view_finance_credit_ledger', 'View advance separate finance ledger'), ('view_combined_ledger', 'View combined credit ledger'), ('view_spare_ledger', 'View spare parts ledger'), ('export_data', 'Export sales/payments to CSV'), ('manage_customers', 'Add/edit customer records'), ('manage_product_models', 'Add/edit/delete product models'), ('manage_inventory', 'Add/edit/delete motorcycles'), ('manage_finance_sales', 'Add/edit/delete finance credit sales'), ('manage_finance_installments', 'Add/edit/delete finance installments'), ('manage_finance_ledger', 'Add/edit/delete finance ledger entries'), ('view_invoices', 'View submitted sales invoices'), ('create_invoices', 'Create new sales invoices and upload them to FBR'), ('manage_fbr_config', 'View & edit FBR configuration (POS ID, tokens, active environment)'), ('manage_companies', 'View & edit company profiles, switch the active company')]},
        ),
    ]
