# Generated by Django 5.2.14 on 2026-09-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_company_alter_staffaccess_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerportalauth',
            name='company_id',
            field=models.IntegerField(null=True),
        ),
        # Backfill from each account's own linked customer - correct
        # regardless of which company happens to be active when this
        # migration runs, since it's derived per-row from the actual
        # customer relationship, not from any "active company" state.
        migrations.RunSQL(
            sql="""
                UPDATE customer_portal_auth cpa
                JOIN customers c ON cpa.customer_id = c.id
                SET cpa.company_id = c.company_id
                WHERE cpa.company_id IS NULL
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
